name: CallSight CI Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  quality-gate:
    name: Quality Gate- Tests and checks
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      DIRECT_URL: ${{ secrets.DIRECT_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        # This will install the dependencies from the lockfile, works like npm ci

      #Check Prisma connection
      - name: Prisma Generate
        run: pnpm --filter @callsight/api prisma:generate

      - name: Lint and Format
        run: pnpm lint

      - name: Typecheck
        run: pnpm typecheck

      - name: Run Tests
        run: pnpm --filter "@callsight/*" test
